### ISSUE TITLE
Commands which are accepted by the normal heroku run break with this plugin

### ISSUE THREAD

**Issue by stof** [heroku/heroku-run#1] opened 2015-05-07 19:06 UTC
All cases I tried are done with a Symfony2 PHP project. To reproduce it, you can deploy this demo app: https://github.com/dzuelke/symfony-standard-heroku
The ``app/console`` file is an executable PHP script with a shebang to find the PHP executable.

``heroku run 'app/console'`` works fine with and without the ``--exit-code`` option.
However, using a command with arguments breaks when using the plugin:

``heroku run 'app/console list'`` works fine, while ``heroku run 'app/console list' --exit-code`` will break.

Note that the heroku-exit-status for the v3 handled this (before it stopped working because of changes in the heroku CLI): https://github.com/glenngillen/heroku-exit-status

**Comment by dickeyxxx** [comment] 2015-05-07 20:29
is there a reason you have the quotes? I think this is expected behavior to fix this bug: https://github.com/heroku/toolbelt/issues/51

If you want to group the run commands you can run it like this now:

```
heroku run -- app/console list
```

**Comment by dickeyxxx** [comment] 2015-05-19 23:57
this is fixed in https://github.com/heroku/heroku-run/commit/e3ca34852857909ce3dd6b12852f1f1fa8c48abe

originally I didn't understand why you wanted to do this, I thought you were just quoting for no reason but then I realized that some people run heroku run with the arguments quoted because that's what they want to send to the dyno, not because they want to group them as a single command.

**Closed by dickeyxxx** 2015-05-19 23:57 UTC
